Repository AY2223S1-CS2103T-W10-3/tp, pull requests merged in 2022-11, with the labels that each got.

#161 Resolve grammar issues in user guide
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#159 Fix exceptions based on tester's comments
  docs/UserGuide.md
  src/main/java/seedu/trackascholar/logic/commands/FindCommand.java
  src/main/java/seedu/trackascholar/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ParserUtil.java
  src/main/java/seedu/trackascholar/model/applicant/Applicant.java
  src/main/java/seedu/trackascholar/model/applicant/Name.java
  src/main/java/seedu/trackascholar/model/applicant/Scholarship.java
  src/main/java/seedu/trackascholar/model/major/Major.java
  src/test/java/seedu/trackascholar/model/applicant/ApplicantTest.java
Labels: type.Bug, severity.Medium

#187 Fix exceptions based on tester's comments
  docs/UserGuide.md
  src/main/java/seedu/trackascholar/logic/commands/EditCommand.java
  src/main/java/seedu/trackascholar/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ParserUtil.java
  src/main/java/seedu/trackascholar/model/applicant/Phone.java
  src/test/data/JsonImportCommandTest/duplicateApplicantTrackAScholar.json
  src/test/data/JsonImportCommandTest/invalidApplicantTrackAScholar.json
  src/test/data/JsonImportCommandTest/typicalApplicantsTrackAScholar.json
  src/test/data/JsonSerializableTrackAScholarTest/invalidApplicantTrackAScholar.json
  src/test/data/JsonSerializableTrackAScholarTest/typicalApplicantsTrackAScholar.json
  src/test/java/seedu/trackascholar/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackascholar/model/applicant/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackascholar/model/applicant/PhoneTest.java
  src/test/java/seedu/trackascholar/testutil/TypicalApplicants.java
Labels: type.Bug, priority.HIGH

#182 Update user guide.
  docs/UserGuide.md
Labels: priority.MEDIUM

#188 Fix Import issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/trackascholar/logic/commands/ImportCommand.java
Labels: severity.Medium

#190 Update PPP and test cases
  docs/AboutUs.md
  docs/team/l1uy1jun.md
  src/main/java/seedu/trackascholar/logic/commands/ClearCommand.java
  src/main/java/seedu/trackascholar/logic/commands/RemoveCommand.java
  src/main/java/seedu/trackascholar/model/Model.java
  src/main/java/seedu/trackascholar/model/TrackAScholar.java
  src/main/java/seedu/trackascholar/model/applicant/Applicant.java
  src/test/data/JsonTrackAScholarStorageTest/invalidAndValidApplicantTrackAScholar.json
  src/test/data/JsonTrackAScholarStorageTest/invalidApplicantTrackAScholar.json
  src/test/java/seedu/trackascholar/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackascholar/logic/commands/EditApplicantDescriptorTest.java
  src/test/java/seedu/trackascholar/logic/commands/EditCommandTest.java
  src/test/java/seedu/trackascholar/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/trackascholar/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackascholar/model/TrackAScholarTest.java
  src/test/java/seedu/trackascholar/model/applicant/ApplicantTest.java
  src/test/java/seedu/trackascholar/model/applicant/NameTest.java
  src/test/java/seedu/trackascholar/model/applicant/ScholarshipContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackascholar/model/applicant/UniqueApplicantListTest.java
  src/test/java/seedu/trackascholar/model/major/MajorContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackascholar/model/major/MajorTest.java
  src/test/java/seedu/trackascholar/storage/JsonAdaptedApplicantTest.java
  src/test/java/seedu/trackascholar/testutil/TypicalApplicants.java
Labels: type.Task, priority.HIGH

#201 Updated developer guide find
  docs/DeveloperGuide.md
Labels: priority.MEDIUM

#206 Update PPP
  docs/DeveloperGuide.md
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/team/darrencsacc.md
Labels: priority.MEDIUM

#211 Update Devoper Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/FilterCommandActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/PinActivityDiagram.puml
  docs/diagrams/PinCommandActivityDiagram.puml
  docs/diagrams/PinSequenceDiagram.puml
  docs/diagrams/RemoveCommandActivityDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/UnPinCommandActivityDiagram.puml
  docs/diagrams/UnPinSequenceDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/FilterCommandActivityDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/PinCommandActivityDiagram.png
  docs/images/PinSequenceDiagram.png
  docs/images/RemoveCommandActivityDiagram.png
  docs/images/RemoveSequenceDiagram.png
  docs/images/UnPinCommandActivityDiagram.png
  docs/images/UnPinSequenceDiagram.png
  docs/index.md
  src/main/java/seedu/trackascholar/logic/parser/FindCommandParser.java
Labels: type.Task, priority.HIGH

#221 Update Documentation and Sample Data
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/trackascholar/model/util/SampleDataUtil.java
Labels: priority.LOW
