Repository AY2223S1-CS2103T-W10-3/tp, pull requests merged in 2022-10, with the labels that each got.

#51 Create Scholarship Status
  src/main/java/seedu/address/model/person/Address.java
Labels: type.Task, priority.HIGH

#55 Snbranch new
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ScholarshipName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.HIGH

#60 Add application status and Update some GUI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Scholarship.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.HIGH

#77 Update documentation and testing
  docs/_config.yml
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableTrackAScholar.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug

#84 Add remove command
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/logic/parser/TrackAScholarParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TrackAScholar.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/ApplicationStatus.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.HIGH

#91 Add Test cases for RemoveCommandParser
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
Labels: type.Task, priority.HIGH

#95 Update documentation and testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Task, priority.HIGH

#101 Update UI for main window
  src/main/java/seedu/trackascholar/logic/commands/ClearCommand.java
  src/main/java/seedu/trackascholar/ui/MainWindow.java
  src/main/java/seedu/trackascholar/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/application_status.png
  src/main/resources/images/mail.png
  src/main/resources/images/phone.png
  src/main/resources/images/scholarship.png
  src/main/resources/images/track_a_scholar_logo.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/trackascholar/commons/util/AppUtilTest.java
Labels: type.Task, priority.HIGH

#93 (Edit)Added SortCommandParserTest.Updated UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/trackascholar/logic/parser/SortCommandParserTest.java
Labels: priority.HIGH

#108 Add EditCommand implementation in DG
  docs/DeveloperGuide.md
Labels: priority.LOW

#109 Update Tags into Majors
  docs/UserGuide.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/trackascholar/logic/commands/AddCommand.java
  src/main/java/seedu/trackascholar/logic/commands/EditCommand.java
  src/main/java/seedu/trackascholar/logic/parser/AddCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/CliSyntax.java
  src/main/java/seedu/trackascholar/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ParserUtil.java
  src/main/java/seedu/trackascholar/logic/parser/Prefix.java
  src/main/java/seedu/trackascholar/model/applicant/Applicant.java
  src/main/java/seedu/trackascholar/model/major/Major.java
  src/main/java/seedu/trackascholar/model/tag/Tag.java
  src/main/java/seedu/trackascholar/model/util/SampleDataUtil.java
  src/main/java/seedu/trackascholar/storage/JsonAdaptedApplicant.java
  src/main/java/seedu/trackascholar/storage/JsonAdaptedMajor.java
  src/main/java/seedu/trackascholar/storage/JsonAdaptedTag.java
  src/main/java/seedu/trackascholar/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/trackascholar/logic/LogicManagerTest.java
  src/test/java/seedu/trackascholar/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackascholar/logic/commands/EditApplicantDescriptorTest.java
  src/test/java/seedu/trackascholar/logic/commands/EditCommandTest.java
  src/test/java/seedu/trackascholar/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/trackascholar/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackascholar/model/TrackAScholarTest.java
  src/test/java/seedu/trackascholar/model/applicant/ApplicantTest.java
  src/test/java/seedu/trackascholar/model/applicant/UniqueApplicantListTest.java
  src/test/java/seedu/trackascholar/model/major/MajorTest.java
  src/test/java/seedu/trackascholar/model/tag/TagTest.java
  src/test/java/seedu/trackascholar/storage/JsonAdaptedApplicantTest.java
  src/test/java/seedu/trackascholar/testutil/ApplicantBuilder.java
  src/test/java/seedu/trackascholar/testutil/ApplicantUtil.java
  src/test/java/seedu/trackascholar/testutil/EditApplicantDescriptorBuilder.java
  src/test/java/seedu/trackascholar/testutil/TypicalApplicants.java
Labels: priority.MEDIUM

#111 Update find command to add new functionality
  src/main/java/seedu/trackascholar/logic/commands/AddCommand.java
  src/main/java/seedu/trackascholar/logic/commands/FindCommand.java
  src/main/java/seedu/trackascholar/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackascholar/model/applicant/Scholarship.java
  src/main/java/seedu/trackascholar/model/applicant/ScholarshipContainsKeywordsPredicate.java
  src/main/java/seedu/trackascholar/model/major/Major.java
  src/main/java/seedu/trackascholar/model/major/MajorContainsKeywordsPredicate.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/trackascholar/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/trackascholar/logic/parser/TrackAScholarParserTest.java
  src/test/java/seedu/trackascholar/model/applicant/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackascholar/model/applicant/ScholarshipTest.java
  src/test/java/seedu/trackascholar/testutil/ApplicantBuilder.java
Labels: type.Enhancement, priority.HIGH

#124 Refine code quality and standard
  src/main/java/seedu/trackascholar/logic/commands/ClearCommand.java
  src/main/java/seedu/trackascholar/logic/commands/ImportCommand.java
  src/main/java/seedu/trackascholar/logic/parser/AddCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/trackascholar/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ImportCommandParser.java
  src/main/java/seedu/trackascholar/logic/parser/ParserUtil.java
  src/main/java/seedu/trackascholar/model/applicant/Applicant.java
  src/main/java/seedu/trackascholar/model/applicant/ApplicationStatus.java
  src/main/java/seedu/trackascholar/model/applicant/ApplicationStatusPredicate.java
  src/main/java/seedu/trackascholar/model/applicant/Email.java
  src/main/java/seedu/trackascholar/model/applicant/Name.java
  src/main/java/seedu/trackascholar/model/applicant/NameContainsKeywordsPredicate.java
  src/main/java/seedu/trackascholar/model/applicant/Phone.java
  src/main/java/seedu/trackascholar/model/applicant/Scholarship.java
  src/main/java/seedu/trackascholar/model/applicant/ScholarshipContainsKeywordsPredicate.java
  src/main/java/seedu/trackascholar/model/major/Major.java
  src/main/java/seedu/trackascholar/model/major/MajorContainsKeywordsPredicate.java
  src/main/java/seedu/trackascholar/model/util/SampleDataUtil.java
  src/main/java/seedu/trackascholar/storage/JsonAdaptedApplicant.java
  src/main/java/seedu/trackascholar/storage/JsonAdaptedMajor.java
  src/main/java/seedu/trackascholar/ui/PersonCard.java
  src/main/java/seedu/trackascholar/ui/PinCard.java
  src/main/resources/view/PinCard.fxml
  src/test/data/JsonSerializableTrackAScholarTest/duplicateApplicantTrackAScholar.json
  src/test/data/JsonSerializableTrackAScholarTest/typicalApplicantsTrackAScholar.json
  src/test/java/seedu/trackascholar/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackascholar/model/ModelManagerTest.java
  src/test/java/seedu/trackascholar/model/applicant/ApplicantTest.java
  src/test/java/seedu/trackascholar/storage/JsonAdaptedApplicantTest.java
  src/test/java/seedu/trackascholar/testutil/ApplicantUtil.java
  src/test/java/seedu/trackascholar/testutil/TypicalApplicants.java
Labels: type.Enhancement, priority.MEDIUM

#130 Fix minor bugs
  docs/UserGuide.md
  src/test/java/seedu/trackascholar/model/applicant/ApplicantTest.java
Labels: type.Bug

#131 Update user guide and sort command message
  docs/UserGuide.md
  docs/images/UserGuideCommands/TrackAScholarOverview.png
  src/main/java/seedu/trackascholar/logic/commands/SortCommand.java
  src/test/java/seedu/trackascholar/logic/commands/SortCommandTest.java
Labels: type.Task

#133 Update UG
  docs/images/UserGuideCommands/sort.png
  src/main/java/seedu/trackascholar/logic/commands/SortCommand.java
Labels: priority.LOW
